#ifndef FR_SHAREDDEFS_H
#define FR_SHAREDDEFS_H

#ifdef _WIN32
#pragma once
#endif

#include "const.h"
#include "KeyValues.h"
#include "Color.h"
#include "shareddefs.h"
#include "fr_mapinfo.h"

//START FR ACHIVEMENTS
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20COMBINE					151
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50COMBINE					152
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100COMBINE				153
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20HUNTERS					154
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50HUNTERS					155
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100HUNTERS				156
#define ACHIEVEMENT_FIREFIGHTRELOADED_REACHMAXLEVEL					157
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ENEMIES				158
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILLTHOUSANDENEMIES			159
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILLMILLIONENEMIES			160
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILLCOMBINEWITHFLECHETTE		161
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10HUNTERSWITHFLECHETTE	162
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ENEMIESONNIGHTMARE		163
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ANTLIONS				164
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50ANTLIONS				165
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ANTLIONS				166
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ANTLIONGUARDS			167
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50ANTLIONGUARDS			168
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ANTLIONGUARDS			169
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ZOMBIES					170
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50ZOMBIES					171
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ZOMBIES				172
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20HEADCRABS				173
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50HEADCRABS				174
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100HEADCRABS				175
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20XENCREATURES			176
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50XENCREATURES			177
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100XENCREATURES			178
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESWITHGRENADE		179
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESZEROBULLETS		180
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ENEMIESNODAMAGE			181
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESATLOWHEALTH		182
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ENEMIESONDEATH			183
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESWITHOWNGRENADE	184
//ENDGAME
#define ACHIEVEMENT_FIREFIGHTRELOADED_COMPLETEDBOSSFIGHT			185
#define ACHIEVEMENT_FIREFIGHTRELOADED_COMPLETEDTUTORIAL				186
//INVASION
#define ACHIEVEMENT_FIREFIGHTRELOADED_MAXKATANAMULTIPLIER			187
#define ACHIEVEMENT_FIREFIGHTRELOADED_SKYBORNEPIN					188
#define ACHIEVEMENT_FIREFIGHTRELOADED_MULTIKILLSTREAK				189
#define ACHIEVEMENT_FIREFIGHTRELOADED_SKYBORNEDECAP					190
//END FR ACHIEVEMENTS

enum EFRLegacyGamemodes
{
	FR_GAMEMODE_DISABLED = -1,
	FR_GAMEMODE_DEFAULT,
	FR_GAMEMODE_COMBINEFIREFIGHT,
	FR_GAMEMODE_XENINVASION,
	FR_GAMEMODE_ANTLIONASSAULT,
	FR_GAMEMODE_ZOMBIESURVIVAL,
	FR_GAMEMODE_FIREFIGHTRUMBLE
};

enum EFRItemTypes
{
	FR_HEALTHKIT = 1,
	FR_BATTERY,
	FR_HEALTHKIT_BIG,
	FR_BATTERY_BIG,
	FR_WEAPON,
	FR_AMMOWEAPON,
	FR_AMMO,
	FR_PERK,
	FR_KASHBONUS,
	FR_SERVERCMD,
	FR_CLIENTCMD,
	FR_EXPBONUS
};

enum EFRPerkIDs
{
	FR_PERK_INFINITEAUXPOWER = 1,
	FR_PERK_INFINITEAMMO,
	FR_PERK_HEALTHREGENERATIONRATE,
	FR_PERK_HEALTHREGENERATION
};

enum EFRUpgradeIDs
{
	FR_UPGRADE_MAXHEALTH,
	FR_UPGRADE_EXPBOOST,
	FR_UPGRADE_KASHBOOST,
	FR_UPGRADE_HEALTHREGENERATION_RANGE,

	FR_UPGRADE_MAX
};

enum EFRDmgCustom
{
	//UNIQUE
	FR_DMG_CUSTOM_NONE = 0,
	FR_DMG_CUSTOM_KICK,	// Marks this as KICK damage
	FR_DMG_CUSTOM_CHARGE, // Marks this as CHARGE damage
	FR_DMG_CUSTOM_CHARGE_GRAPPLE, // Marks this as CHARGE damage from the Grapple
	FR_DMG_CUSTOM_HUNTER_AR2, // Damaged by a Ministrider
	FR_DMG_CUSTOM_HUNTER_RAILGUN, // Damaged by a Rail Hunter

	//NONUNIQUE
	FR_DMG_CUSTOM_NONUNIQUE_FORCEKNOCKBACK, // Damage forces NPC knockback

	FR_DMG_CUSTOM_END // END
};

#define MAX_LEVEL 20

//FR COLORS
#define COLOR_FR_OLD		Color("#FF5454FF")
#define COLOR_FR			Color("#0078FFFF")

//FR FUN COLORS
#define COLOR_PURPLE		Color("#C79AF5FF")
#define COLOR_CYAN			Color("#49D8F5FF")
#define COLOR_TURQUOISE		Color("#38F5D2FF")
#define COLOR_PINK			Color("#ED8EDCFF")
#define COLOR_MAGENTA		Color("#FF00FFFF")
#define COLOR_YELLOW_NEW	Color("#F5C449FF")

//tf2 quality/skin colors
//items
#define COLOR_UNIQUE		Color("#FFD700FF")
#define COLOR_VINTAGE		Color("#476291FF")
#define COLOR_GENUINE		Color("#4D7455FF")
#define COLOR_STRANGE		Color("#CF6A32FF")
#define COLOR_UNUSUAL		Color("#8650ACFF")
#define COLOR_HAUNTED		Color("#38F3ABFF")
#define COLOR_COLLECTORS	Color("#AA0000FF")
#define COLOR_COMMUNITY		Color("#70B04AFF")
#define COLOR_VALVE			Color("#A50F79FF")
//paints
#define COLOR_CIVILIAN		Color("#B0C3D9FF")
#define COLOR_FREELANCE		Color("#5E98D9FF")
#define COLOR_MERCENARY		Color("#4B69FFFF")
#define COLOR_COMMANDO		Color("#8847FFFF")
#define COLOR_ASSASSIN		Color("#D32CE6FF")
#define COLOR_ELITE			Color("#EB4B4BFF")

//Available Teams (represents killfeed/killog colors):
//TEAM_ANY				-2 (Used for random teams)

//Generic Colors:

#define TEAM_RED		2 //(Default for NPCs)
#define TEAM_BLUE		3
#define TEAM_YELLOW		4
#define TEAM_GREEN		5
#define TEAM_GREY		6
#define TEAM_WHITE		7
#define TEAM_BLACK		8
#define TEAM_PURPLE		9
#define TEAM_ORANGE		10 //(Default for Rare NPCs)
#define TEAM_CYAN		11
#define TEAM_TURQUOISE	12
#define TEAM_PINK		13
#define TEAM_MAGENTA	14 //(Default for Boss/Advisor/Advisor Drones)

//Special Colors:

#define TEAM_SMOD		15
#define TEAM_FR			16

//TF2 Quality/War Paint Colors:

#define TEAM_UNIQUE		17
#define TEAM_VINTAGE	18
#define TEAM_GENUINE	19
#define TEAM_STRANGE	20 
#define TEAM_UNUSUAL	21
#define TEAM_HAUNTED	22
#define TEAM_COLLECTORS	23
#define TEAM_COMMUNITY	24
#define TEAM_VALVE		25
#define TEAM_CIVILIAN	26
#define TEAM_FREELANCE	27
#define TEAM_MERCENARY	28
#define TEAM_COMMANDO	29
#define TEAM_ASSASSIN	30
#define TEAM_ELITE		31

//CHANGE THESE IF YOU ADD A NEW TEAM
#define TEAM_NPC_FIRST	TEAM_RED
#define TEAM_NPC_LAST	TEAM_ELITE

typedef struct
{
	int id;
	Color col;
	const char* name;
} FRTeam_t;

class CFRTeamLoader
{
public:

	static FRTeam_t FRTeamMap[];
	static Color GetColorForTeam(int iTeamNumber);
	static const char* GetNameForTeam(int iTeamNumber);
	static void LoadColors(Color *colorArray);
};

class FRKeyValuesLoader
{
public:
	void LoadEntries(const char* fileName, const char* kvHeader);
	bool FindEntry(string_t query);
	string_t	GrabRandomEntryString(void);
	CUtlVector<string_t> m_storedVector;
};

extern const char* UTIL_FR_GetVersion(bool cmd = false);

#endif // FR_SHAREDDEFS_H